### ISSUE TITLE
user can start their car

### ISSUE THREAD

**Issue by john-hc-hwang** [john-hc-hwang/driving-game#2]
## 💰 Motivation

It's a driving game, duh!

## 📐 Plan

Move the car a few pixels every 16 milliseconds when the user presses space.

## ✅ Task List

- [x] Move the car to the right a few pixels every 16 ms when the user presses space.
- [x] Make a function to move the car few pixels
- [x] use setInterval to trigger every 16ms
