### ISSUE TITLE
user can stop their car

### ISSUE THREAD

**Issue by john-hc-hwang** [john-hc-hwang/driving-game#4]
## 💰 Motivation

If the user cannot stop their car, it goes off the page.

## 📐 Plan

Stop the car if the user presses space again.

## ✅ Task List

- [x] Stop the car if the user presses space again.
- [x] Make a spaceIndex and keep track to see if even or odd.
- [x] if spaceIndex is odd, then stop
- [x] if spaceIndex is even, then go
