### ISSUE TITLE
user can turn their car

### ISSUE THREAD

**Issue by john-hc-hwang** [john-hc-hwang/driving-game#5]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x] Rotate the image with CSS classes when the user presses an arrow key.
- [x] Make css classes west, east, north, south
- [x] Use JS to add class appropriately
